In [1]:
import pandas as pd

df = pd.read_csv("../data/metadata.csv")

print(df.shape)
df.head()

(1636, 32)

,building_id,site_id,building_id_kaggle,site_id_kaggle,primaryspaceusage,sub_primaryspaceusage,sqm,sqft,lat,lng,...,yearbuilt,date_opened,numberoffloors,occupants,energystarscore,eui,site_eui,source_eui,leed_level,rating
0,Panther_lodging_Dean,Panther,NaN,0.0,Lodging/residential,Residence Hall,508.8,5477.0,28.517689,-81.379039,...,1989.0,NaN,NaN,NaN,NaN,271,NaN,NaN,NaN,NaN
1,Panther_lodging_Shelia,Panther,NaN,0.0,Lodging/residential,Residence Hall,929.0,10000.0,28.517689,-81.379039,...,1992.0,NaN,NaN,NaN,NaN,62,NaN,NaN,NaN,NaN
2,Panther_lodging_Ricky,Panther,NaN,0.0,Lodging/residential,Residence Hall,483.1,5200.0,28.517689,-81.379039,...,2016.0,NaN,NaN,NaN,NaN,534,NaN,NaN,NaN,NaN
3,Panther_education_Rosalie,Panther,0.0,0.0,Education,Research,690.5,7432.0,28.517689,-81.379039,...,2008.0,NaN,NaN,NaN,NaN,276,NaN,NaN,NaN,NaN
4,Panther_education_Misty,Panther,1.0,0.0,Education,Research,252.7,2720.0,28.517689,-81.379039,...,2004.0,NaN,NaN,NaN,NaN,375,NaN,NaN,NaN,NaN

In [2]:
df.columns.tolist()

['building_id',
 'site_id',
 'building_id_kaggle',
 'site_id_kaggle',
 'primaryspaceusage',
 'sub_primaryspaceusage',
 'sqm',
 'sqft',
 'lat',
 'lng',
 'timezone',
 'electricity',
 'hotwater',
 'chilledwater',
 'steam',
 'water',
 'irrigation',
 'solar',
 'gas',
 'industry',
 'subindustry',
 'heatingtype',
 'yearbuilt',
 'date_opened',
 'numberoffloors',
 'occupants',
 'energystarscore',
 'eui',
 'site_eui',
 'source_eui',
 'leed_level',
 'rating']

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1636 entries, 0 to 1635
Data columns (total 32 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   building_id            1636 non-null   str
 1   site_id                1636 non-null   str
 2   building_id_kaggle     1449 non-null   float64
 3   site_id_kaggle         1599 non-null   float64
 4   primaryspaceusage      1615 non-null   str
 5   sub_primaryspaceusage  1615 non-null   str
 6   sqm                    1636 non-null   float64
 7   sqft                   1636 non-null   float64
 8   lat                    1399 non-null   float64
 9   lng                    1399 non-null   float64
 10  timezone               1636 non-null   str
 11  electricity            1578 non-null   str
 12  hotwater               185 non-null    str
 13  chilledwater           555 non-null    str
 14  steam                  370 non-null    str
 15  water                  146 non-null    str
 16  irrigation             37 non-null     str
 17  solar                  5 non-null      str
 18  gas                    177 non-null    str
 19  industry               579 non-null    str
 20  subindustry            579 non-null    str
 21  heatingtype            215 non-null    str
 22  yearbuilt              817 non-null    float64
 23  date_opened            21 non-null     str
 24  numberoffloors         441 non-null    float64
 25  occupants              230 non-null    float64
 26  energystarscore        163 non-null    str
 27  eui                    299 non-null    str
 28  site_eui               163 non-null    str
 29  source_eui             163 non-null    str
 30  leed_level             16 non-null     str
 31  rating                 184 non-null    str
dtypes: float64(9), str(23)
memory usage: 409.1 KB

In [4]:
df[['building_id', 'site_id', 'primaryspaceusage']].head(10)

                 building_id  site_id    primaryspaceusage
0       Panther_lodging_Dean  Panther  Lodging/residential
1     Panther_lodging_Shelia  Panther  Lodging/residential
2      Panther_lodging_Ricky  Panther  Lodging/residential
3  Panther_education_Rosalie  Panther            Education
4    Panther_education_Misty  Panther            Education
5       Panther_office_Daina  Panther               Office
6   Panther_education_Mattie  Panther            Education
7     Panther_office_Woodrow  Panther               Office
8    Panther_education_Diann  Panther            Education
9     Panther_education_Gina  Panther            Education

In [6]:
df['site_id'].nunique()

19

In [5]:
df['building_id'].nunique()

1636

In [7]:
df ['primaryspaceusage'].value_counts().head(20)

primaryspaceusage
Education                        617
Office                           307
Entertainment/public assembly    204
Lodging/residential              168
Public services                  166
Other                             29
Healthcare                        29
Parking                           24
Warehouse/storage                 15
Manufacturing/industrial          13
Retail                            12
Services                          11
Technology/science                 7
Food sales and service             6
Utility                            4
Religious worship                  3
Name: count, dtype: int64

In [8]:
df.isna().sum().sort_values(ascending=False)

solar                    1631
leed_level               1620
date_opened              1615
irrigation               1599
water                    1490
energystarscore          1473
site_eui                 1473
source_eui               1473
gas                      1459
rating                   1452
hotwater                 1451
heatingtype              1421
occupants                1406
eui                      1337
steam                    1266
numberoffloors           1195
chilledwater             1081
industry                 1057
subindustry              1057
yearbuilt                 819
lng                       237
lat                       237
building_id_kaggle        187
electricity                58
site_id_kaggle             37
sub_primaryspaceusage      21
primaryspaceusage          21
timezone                    0
building_id                 0
site_id                     0
sqm                         0
sqft                        0
dtype: int64

In [9]:
df[['building_id', 'site_id', 'primaryspaceusage']].head(20)

                      building_id  site_id              primaryspaceusage
0            Panther_lodging_Dean  Panther            Lodging/residential
1          Panther_lodging_Shelia  Panther            Lodging/residential
2           Panther_lodging_Ricky  Panther            Lodging/residential
3       Panther_education_Rosalie  Panther                      Education
4         Panther_education_Misty  Panther                      Education
5            Panther_office_Daina  Panther                         Office
6        Panther_education_Mattie  Panther                      Education
7          Panther_office_Woodrow  Panther                         Office
8         Panther_education_Diann  Panther                      Education
9          Panther_education_Gina  Panther                      Education
10         Panther_education_Tina  Panther                      Education
11        Panther_lodging_Russell  Panther            Lodging/residential
12  Panther_education_Guillermina  Panther                      Education
13           Panther_lodging_Amos  Panther            Lodging/residential
14      Panther_education_Vincent  Panther                      Education
15      Panther_education_Shelton  Panther                      Education
16           Panther_office_Karla  Panther                         Office
17        Panther_assembly_Denice  Panther  Entertainment/public assembly
18       Panther_education_Sophia  Panther                      Education
19         Panther_lodging_Bonnie  Panther            Lodging/residential

In [10]:
df.groupby('site_id').size().sort_values(ascending=False)

site_id
Rat         305
Hog         163
Lamb        147
Fox         137
Panther     136
Bull        124
Cockatoo    124
Eagle       106
Bear         92
Gator        74
Robin        52
Peacock      47
Bobcat       36
Wolf         36
Swan         21
Moose        15
Shrew         9
Mouse         7
Crow          5
dtype: int64